:page-layout: standard_toc
:page-title: Year 8 IT - Common Test
:icons: font

= Year 8 IT - Common Test: JavaScript =

*Weight:* 30% +
*Date:* Wednesday 25 August 2021 (Week 6) - during your normal lesson time

== Changelog ==

This task was last updated on *Monday 26 July 2021*.

If any changes are made to the task they will be itemised here for ease of identification.

== Task Context ==

The focus of this task is to allow students to demonstrate their level of coding skill in JavaScript.

== Task Description ==

* This is a 45 minute common test during normal lesson time
* The test will start promptly 5 minutes after the second bell. Students must arrive with sufficient time to login to their computers and ED STEM prior to the commencement of the test, along with open/access any other resources which you would like to use during the test.
* The test will require students to code a number of JavaScript programs to meet certain specifications, using a template provided within ED STEM.
* The test may draw upon all content which has been covered in the course up to Friday 20 August 2021. Note, we will still be completing activities after this date which cover examinable material, and you should review these activities as part of your revision. However, any new content will not be examined — for clarity, you will be informed whether the material being covered is new and thus non-examinable, or review of existing material which is examinable.
* Your code in the test does not need to be commented. However, proper naming of variables (to reflect their purpose) is required, along with correct indentation of code. There may be some existing comments written within the template to guide each task and challenge.
* In preparation for this task, students should review concepts including (but not limited to) data types and variables, input and output, logic and conditionals, methods, arrays and loops.
* The test will be conducted on computers and is completely open-resource. Any resources (including the internet, textbooks, handwritten or electronic notes) may be used. However, email and any other form of real-time (or near real-time) communication must not be used — while students can use resources to research how to solve the questions they may not communicate with anyone else during the test.
* Keep in mind that even though this test is open-resource, it is essential that all students undertake sufficient revision. Referring to other resources is only useful if you need to quickly reference or look-up something. If you do not already have a firm grasp of JavaScript then you cannot expect to research and understand completely new concepts, then answer the questions, within the time frame.
* There will be a practice test published by the end of Week 4, so that every student has the opportunity to practice and review the concepts being assessed

== Practice Tests ==

For revision purposes, there is a *JavaScript practice quiz* available in ED STEM under the Lessons tab.

=== Reporting Criteria

* Demonstrating an understanding of core programming concepts, particularly variables, data types, and control structures
* Understanding appropriate use and implementation of functions and data structures

== Hints and Pro Tips ==

Here you can find various hints and tips to help with your preparation for the common test.

* It is highly advisable that you create some kind of notes page (also known as a "cheat-sheet") and/or electronic versions of common code (with an explanation as to their purpose). This will provide a extremely valuable and quick reference for you during the test, saving you from having to search through your book or online. It also has the added benefit that by compiling this information you will essentially be revising all these items!
