:page-layout: standard
:page-title: Year 8 IST - Array Activities
:icons: font

= Year 8 IST - Array Activities =

== Instructions ==

All these tasks should be completed in separate HTML files in your `Array Activities` ED STEM workspace. Name each file `activityX.html` (e.g. activity1.html, activity2.html, etc.).

== Task One (a) ==

Create a program that stores the following numbers in an array: 5, 8, 12, 25, 30, 36, 40, 45, 50.

Loop through the array and display if each number is even or odd.

It should look like:

5 is odd.

8 is even.

etc.

== Task One (b) ==

Copy and modify the above program so that it displays odd and even numbers, using one line for each.

It should look like:

Odd numbers: 5, 25, 45

Even numbers: 8, 12, 30, etc.

== Task Two ==

Create a program that stores 5 names in an array, and their 5 favourite foods in a second array.

Display what each person's favourite food is.

It should look like:

Mr Head First likes to eat baked potato. (If name is "Mr Head First" and favourite food is "baked potato")

etc.

== Task Three (a) ==

Create a program that stores an array of 6 random numbers between 1 and 10.

Calculate the total of all the numbers.

Prompt the user to guess the total, and compare this to your answer.

Alert the user to tell them if their answer was correct or incorrect.

== Task Three (b) ==

Modify the program so that it also calculates the mode and the mean.

For the mode:

- If all numbers are different, than the correct answer for the mode should be "None".

- If there is more than one mode, if the user types in any of them, it should tell them they are correct. As a bonus, you can also list the other modes.

For the mean:

- If the average results in a decimal number, this should be rounded off to 2 decimal places (if required).

- The user needs to guess correct to 2 decimal places (if required).
