:page-published: false

Any submitted work is to be your own. There are serious consequences for submitting work which is taken from another person, even if they give it to you voluntarily. To decide if you have written the material, we may need to question you about your understanding of the topic. Please be careful when presenting ideas which are not entirely your own; reference such material thoroughly.

*Remember, if you take someone else's work (e.g. code) and make some slight modifications (e.g. renaming variables, moving some of the code around) but the underlying algorithm is the same or _very_ similar then that is still plagiarism as you are presenting their work as your own. In fact, making these slight modifications is even more serious since it shows intent to try and conceal the fact you are plagiarising.*

The essence of all work that you submit to this course must be your own. Collaboration on homework, assignments, and projects is not permitted except to the extent that you may ask classmates and others for help so long as that help does not reduce to another doing your work for you. Generally speaking, when asking for help, you may show your code to others, but you may not view theirs, so long as you and they respect this policy's other constraints.

Collaboration on projects is permitted to the extent prescribed by its specification (for example, if the particular project allows you to complete it in a group).

Below are rules of thumb that (inexhaustively) characterize acts that the course considers reasonable and not reasonable. If in doubt as to whether some act is reasonable, do not commit it until you solicit and receive approval in writing from your teacher. Acts considered not reasonable by the course are handled harshly — such as an unsatisfactory or failing grade for work submitted, along with the issue of an academic detention.

=== Reasonable

* Communicating with classmates about questions, activities, and assignments in English (or some other spoken language).
* Discussing the course's material with others in order to understand it better.
* Helping a classmate identify a bug in his or her code at IT tutorials or elsewhere.
* Incorporating a few lines of code that you find online or elsewhere into your own code, provided that those lines are not themselves solutions to assigned problems and that you cite/reference the lines' origins.
* Showing code that you've written to someone, possibly a classmate, so that he or she might help you identify and fix a bug.
* Sharing a few lines of your own code online so that others might help you identify and fix a bug.
* Turning to your teacher for help.
* Turning to the web or elsewhere for instruction beyond the course's own, for references, and for solutions to technical difficulties, but not for outright solutions to problem set's problems or your own final project.
* Whiteboarding solutions to activities with others using diagrams or pseudocode but not actual code.
* Working with (and even paying) a tutor to help you with the course, provided the tutor does not do your work for you.

=== Not Reasonable

* Sending someone else a large portion of your source code.
* Asking a classmate to see his or her solution to a problem before submitting your own.
* Having someone else complete all, or a substantive amount of, the work for you.
* Decompiling, deobfuscating, or disassembling the teacher's solutions.
* Failing to cite (as with comments) the origins of code or techniques that you discover outside of the course's own lessons and integrate into your own work, even while respecting this policy's other constraints.
* Giving or showing to a classmate a solution when they are struggling to solve it.
* Looking at another individual's work during a test or quiz.
* Paying or offering to pay an individual for work that you may submit as (part of) your own.
* Providing or making available solutions to individuals who might take this course in the future.
* Searching for or soliciting outright solutions to activities online or elsewhere.
* Splitting a the workload with another individual and combining your work, unless the work has been specifically set as a group task.
* Submitting (after possibly modifying) the work of another individual beyond the few lines allowed herein.
* Turning to humans (besides your teacher) for help or receiving help from humans (besides your teacher) during a quiz or test.
* Viewing another's solution to an activity and basing your own solution on it.
* Sharing the details of an assessment task, such as a test, which you have done but other students may not have completed yet (or asking for the details of an assessment task from someone who has already completed that task).

[footnote]##Based upon Harvard University https://cs50.harvard.edu/[CS50's^] Academic Honesty Policy, used and adapted with permission. Thanks to Prof. David J. Malan.##
